### ISSUE TITLE
Черный экран 

### ISSUE THREAD

**Issue by maxuko** [farag2/Windows-10-Setup-Script#15]
День добрый,
После применения скрипта (без ошибок).

При перезагрузке, после ввода пароля , черный экран, мин 5-7 (при этом ПК работает и через кон+шифт+еск   запускается диспетчер задач и приложения через него).
 Потом появляется заставка и меню пуск.

https://ibb.co/CvqW5cg

Такая проблема на всех ПК, где применялся скрипт шт 5.
10 -1903.

**Comment by farag2** [comment]
Я в недоумении. Скрипт применяется на абсолютно разных ПК практически каждый день. Такой проблемы нет. Разрядность ОС и комплектующие ПК?

**Comment by citizen0ne** [comment]
Проблема в драйвере видеокарты.23:59, 13 ноября 2019 г., farag2 <notifications@github.com>:Я в недоумении. Скрипт применяется на абсолютно разных ПК практически каждый день. Такой проблемы нет. Разрядность ОС и комплектующие ПК?

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
-- Отправлено из мобильного приложения Яндекс.Почты

**Comment by farag2** [comment]
Значит, проблемы нет?)

**Comment by citizen0ne** [comment]
Есть, аппаратная, можно закрывать инцидент ))0:03, 14 ноября 2019 г., farag2 <notifications@github.com>:Значит, проблемы нет?)

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.
-- Отправлено из мобильного приложения Яндекс.Почты

**Comment by farag2** [comment]
Все-таки надо было дрова обновить. Грех это не обновлять. :)

**Comment by maxuko** [comment]
Первое, что было сделано - это переставлены драйвера видео GTX1050) Результат 0.
ПК разной конфигурации, как выполнение скрипта влияет на драйвер видео, после чего он перестает корректно работать? 

Будем копать в эту сторону) Спасибо.

**Comment by farag2** [comment]
@maxuko, никак не влияет, ибо скрипт — это набор команд. Ни одна команда не может влиять на драйвер. :)
