### ISSUE TITLE
Update README.md with features list?

### ISSUE THREAD

**Issue by xRiot** [farag2/Windows-10-Setup-Script#2]
Currently this project has a very minimalist and unclear README.md overview and furthermore the comments inside the project files are in Russian, could we arrange a better documentation in English @farag2?

Thanks.

**Comment by farag2** [comment]
Hello. I'll update readme file and add english comments when 1903 release. I think it could happen this week.
Is the description from for example https://github.com/Disassembler0/Win10-Initial-Setup-Script suitable?
I didn't provide description, because only me and some forum members use this script. If even another users create such topics, I'll do that.

**Comment by xRiot** [comment]
Thanks for replying on such short notice @farag2.

The best approach would be to create a detailed list with enhancements that you offer and short introduction, the format you linked is a good start!

**Comment by farag2** [comment]
Ok. Give me some days. Is it OK, if there will be comment in english and below comment in russian?
Like this:
# comment
# комментарий

**Comment by xRiot** [comment]
You could aim for the solution that best fits your backers/target audience.

I'm speaking from my prior experience, I'd highly recommend any repository to use only English for comments and main documentation. Attempting to do it in multiple languages extends the size as well as adds a whole new scope of work to the project.

You should always proceed in a way that doesn't involve too much micro moderation between each update :).

**Comment by farag2** [comment]
OK, Google. Thank you, Siri. :)

**Comment by farag2** [comment]
@xRiot,
**is it much better?**
e.g.
```powershell
# Turn off diagnostics tracking services
# Отключить службы диагностического отслеживания
$services = @(
	# Connected Devices Platform service
	# Служба платформы подключенных устройств
	"CDPSvc",
	# Connected User Experiences and Telemetry
	# Функциональные возможности для подключенных пользователей и телеметрия
	"DiagTrack",
	# Data Usage
	# Использование данных
	"DusmSvc",
	# SSDP Discovery
	# Обнаружение SSDP
	"SSDPSRV")
Foreach ($service in $services)
{
	Get-Service -ServiceName $service | Stop-Service -Force
	Get-Service -ServiceName $service | Set-Service -StartupType Disabled
}
```

**Comment by xRiot** [comment]
Naturally, good work @farag2!

**Comment by farag2** [comment]
I think, I've done translating script. May be upload tomorrow.

**Comment by farag2** [comment]
I've updated all script. Please help to improve the translation, if needed.

**Comment by RoyiAvital** [comment]
Is there a way to control, one by one, what is being done?
It seems the script is doing a lot of things behind the scene and it would be great to have ste by step option for Yes / No / Skip.

**Comment by farag2** [comment]
@RoyiAvital, hello. Unfortunately, there is no way due to command line interface. So you must open the code and comment out what you do not to be executed or update the code. I do not want to add

```powershell
$Host.UI.PromptForChoice($Title, $Message, $Options, $DefaultChoice)
```

to the every function. Anyway yo can add it everywhere you want.
P.S. Now we are cooking a C# GUI version of script. No ETA.

[![ko-fi](https://imgur.com/a/RU8xU5s)]
