### ISSUE TITLE
options menu for UI changes 

### ISSUE THREAD

**Issue by aminya** [farag2/Windows-10-Setup-Script#31]
If we could have an options menu similar to the uninstall list, we could customize the UI changes easier.

![image](https://user-images.githubusercontent.com/16418197/85322010-3f14c100-b48b-11ea-9221-d679bf5f8c76.png)

Related #28

**Comment by farag2** [comment]
Of course yes. It will be in GUI version of the script (no ETA). But this script has CLI interface. And if there is any menu that's only because it is better for user to operate with arrays of apps to be uninstalled. Previous versions don't have it; only arrays of excluded and included apps.
So wait for a GUI version. A sketch:
