### ISSUE TITLE
PS script failure due to Bitdefender false positive detection for "C:\Windows\System32\Tasks\Setup Script\Windows Cleanup"

### ISSUE THREAD

**Issue by tomlog01** [farag2/Windows-10-Setup-Script#35]
My antivirus software (Bitdefender Total Security) gives me a false positive during execution of the Powershell script:

"The file C:\Windows\System32\Tasks\Setup Script\Windows Cleanup is infected with Heur.BZC.WBO.Boxter.501.4B1E4D92. The threat was successfully blocked, your device is safe."

After the Windows task has been aborted, the file "C:\Windows\System32\Tasks\Setup Script\Windows Cleanup" is no longer present (not even quarantined). 
Is it possible to save the generated task file otherwise, so that I can request a whitelisting by Bitdefender Support?

**Comment by farag2** [comment]
@tomlog01, hello. I do not know how to configure the AV, due to I do not use any kind of AVs exept built-in Defender. But I know why there is a false positive alert: if you read the entire script you could notice that I had to obfuscate schedule task creation code. It's too big, and I saved it to the $EncodedScript variable: https://github.com/farag2/Windows-10-Setup-Script/blob/651591cf3e7e5cdac2394c6441751e39e000999b/Win%2010%202004.ps1#L2730
And here I described how to decode this string: https://github.com/farag2/Windows-10-Setup-Script/blob/651591cf3e7e5cdac2394c6441751e39e000999b/Win%2010%202004.ps1#L2744

So what I would do: temporarily disable AV, run the script and then exclude

```
"C:\Windows\System32\Tasks\Setup Script\Windows Cleanup"
```

folder.
