### ISSUE TITLE
Kaspersky 

### ISSUE THREAD

**Issue by zerohd** [farag2/Windows-10-Setup-Script#38]
* Win.10.2004.4.5.4

when starting the script , Kaspersky sees it as a virus and remove it .

**Comment by farag2** [comment]
LOL.

Warning: Some third-party Antivirus may detect this script or it's part as a false positive due to this variable:

https://github.com/farag2/Windows-10-Setup-Script/blob/298307bafee70b55ea00d9cba7a9e14ea6e4f5a4/Win%2010%202004.ps1#L2689

So you might need to disable tamper protection from your Antivirus settings (or use Microsoft Defender, cos it's much better) and re-enable it after run the script and reboot.

**Comment by zerohd** [comment]
ah i see!

**Comment by farag2** [comment]
I'll try to avoid that method in the next release
